apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: go-rimegate-dogelink-com
  name: go-rimegate-dogelink-com
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: go-rimegate-dogelink-com
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-rimegate-dogelink-com
    spec:
      containers:
      - env:
        - name: GRAFANA_HOST
          value: http://grafana.monitoring.svc.cluster.local:3000
        # Remove this env var if Grafana username/password forwarding is used.
        - name: GRAFANA_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: rimegate-grafana-api-token
              key: rimegate-grafana-api-token
        image: 172.16.16.2:2443/go:rimegate-4f93812
        imagePullPolicy: IfNotPresent
        name: rimegate
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 1Gi
          requests:
            cpu: 150m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: go-rimegate-dogelink-com
  namespace: monitoring
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-rimegate-dogelink-com
  sessionAffinity: None
  type: ClusterIP